name: P2WInventory
version: '${project.version}'
main: chch.p2winventory.P2WInventory
api-version: '1.20'
commands:
  getplayer:
    usage: /getplayer
    description: Get info about player
  add:
    usage: /add <player> <type of data> <amount>
    permission: '*'
  remove:
    usage: /remove <player> <type of data> <amount>
    permission: '*'